[package]
name = "RustBoy"
version = "0.1.0"
authors = ["tobyw"]

[dependencies]
hex = "0.2.0"
csv = "1.0.0-beta.4"
piston = "0.33.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.39.0"
piston2d-opengl_graphics = "0.46.0"
image = "0.15.0"
piston_window = "0.70.0"